### ISSUE TITLE
Database suggestion

### ISSUE THREAD

**Issue by fbonnardel** [glycoinfo/glic-old#9]
Dear glycoinformatics consortium team,

I saw you already propose SugarBind in the DB ressources links.
I would like to suggest you the websites:

UniLectin
https://www.unilectin.eu/
UniLectin exploration platform for manually curated and predicted lectins. UniLectin provides information on the lectin proteins and structures for a large number of families.

GlyConnect
https://glyconnect.expasy.org/browser/
Relations between glycan, proteins, taxonomy, expression tissue and diseases

Is it possible to add them on your websites in the ressources links?

Cheers,

BONNARDEL François
UniLectin database developper
PhD student in lectin bioinformatics study (CERMAV - SIB PIG)

**Comment by kiyoko** [comment]
Dear Dr. Bonnardel,

I apologize for the very delayed response!

I've added you to the GLIC group, so I would appreciate it if you could go ahead and add these databases directly to the GLIC database list.

Thank you,

Kiyoko
